# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Links: /links
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts


# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:


# Baidu share
baidushare: true

# widget behavior
archive_type: 'monthly'
show_count: false
